"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Language = "en" | "es";

type Dictionary = Record<string, string>;

const dictionaries: Record<Language, Dictionary> = {
  en: {
    navMarkets: "Markets",
    navAcademy: "Academy",
    navHowItWorks: "How It Works",
    navCommunity: "Community",
    poweredByPolymarket: "Powered by Polymarket",
    demoTrading: "Demo Trading",
    signOut: "Sign out",
    logIn: "Log In",
    getStarted: "Get Started",
    closeMenu: "Close menu",
    openMenu: "Open menu",
    poweredByPolymarketApi: "Powered by Polymarket API",
    liveData: "Live Data",
    heroTitleLine1: "Paper Trading",
    heroTitleLine2: "for Polymarket",
    heroSubtitle:
      "Learn to trade prediction markets without risking real money. Practice with live Polymarket data and master the odds before going live.",
    startPredicting: "Start Predicting",
    browseMarkets: "Browse Markets",
    signIn: "Sign in",
    or: "or",
    createAccount: "Create account",
    accountHint: "Create a free account to track your progress and save your portfolio.",
    zeroRisk: "Zero Financial Risk",
    realPrices: "Real Polymarket Prices",
    paperMode: "Paper Trading Mode",
    product: "Product",
    resources: "Resources",
    legal: "Legal",
    company: "Company",
    footerBrandDesc: "Free prediction market simulator with real Polymarket data.",
    helpCenter: "Help Center",
    documentation: "Documentation",
    blog: "Blog",
    tutorials: "Tutorials",
    terms: "Terms of Service",
    privacy: "Privacy Policy",
    riskDisclosure: "Risk Disclosure",
    about: "About Us",
    careers: "Careers",
    press: "Press",
    contact: "Contact",
    attrTitle: "Powered by Polymarket",
    attrTextPrefix: "All market data comes from",
    attrTextMiddle: ", the leading decentralized prediction market. Ready to trade with real funds?",
    attrTextLink2: "Visit Polymarket directly",
    allRightsReserved: "All rights reserved.",
    dataPoweredBy: "Data powered by",
    welcomeBack: "Welcome back",
    loginDescription: "Sign in to access the prediction markets demo",
    password: "Password",
    enterPassword: "Enter your password",
    signingIn: "Signing in...",
    dontHaveAccount: "Don't have an account?",
    backToHome: "Back to home",
    virtualFundsNotice:
      "By signing in, you agree to practice trading with virtual funds only. No real money is involved.",
    createAccountTitle: "Create account",
    signUpDescription: "Start practicing with $100,000 in virtual funds",
    displayName: "Display Name",
    optional: "optional",
    yourNickname: "Your nickname",
    min6Chars: "Min. 6 characters",
    confirmPassword: "Confirm Password",
    repeatPassword: "Repeat your password",
    creatingAccount: "Creating account...",
    whatYouGet: "What you get:",
    benefitBalance: "$100,000 virtual trading balance",
    benefitRealtime: "Real-time prediction market data",
    benefitPractice: "Practice trading without risk",
    benefitTrack: "Track your performance",
    alreadyHaveAccount: "Already have an account?",
    createAccountNotice:
      "By creating an account, you agree to practice trading with virtual funds only. No real money is involved.",
    passwordsDontMatch: "Passwords do not match",
    passwordTooShort: "Password must be at least 6 characters",
    authUnexpectedError: "An error occurred",
    checkYourEmail: "Check your email",
    sentConfirmationLink: "We sent you a confirmation link",
    verifyEmailHelp:
      "Click the link in your email to verify your account and start trading with virtual funds.",
    didntReceiveEmail: "Didn't receive an email? Check your spam folder or",
    tryAgain: "try again",
    backToLogin: "Back to login",
    authSomethingWrong: "Something went wrong",
    authUnexpectedErrorLong: "An unexpected error occurred during authentication.",
    errorPrefix: "Error:",
    goDemo: "Enter demo",
    authPanelTitle: "Demo access panel",
    authPanelDescription: "Create your account or sign in to use the simulator",
    loginTab: "Sign in",
    signupTab: "Create account",
    startDemoTrading: "Start Demo Trading",
    startsWithFunds: "Starts with $100,000 in virtual funds",
    tradeRealWorldEvents: "Trade on real-world events with prediction markets",
    predictionMarkets: "Prediction Markets",
    realMarketsPowered: "Real markets powered by Polymarket",
    loadingMarkets: "Loading markets...",
    marketsAvailable: "markets available",
    portfolio: "Portfolio",
    balance: "Balance",
    invested: "Invested",
    positions: "Positions",
    recentTrades: "Recent Trades",
    shares: "shares",
    placeOrder: "Place Order",
    placeOrderDesc: "Trade on this prediction market with your demo balance.",
    yes: "Yes",
    no: "No",
    chance: "chance",
    amountUsd: "Amount (USD)",
    pricePerShare: "Price per share",
    maxReturn: "Max return",
    buyYes: "Buy Yes",
    buyNo: "Buy No",
    insufficientBalance: "Insufficient balance. Available:",
    unknown: "Unknown",
    other: "Other",
    ended: "Ended",
    today: "Today",
    tomorrow: "Tomorrow",
    tbd: "TBD",
    allCategory: "All",
    politicsCategory: "Politics",
    sportsCategory: "Sports",
    cryptoCategory: "Crypto",
    popCultureCategory: "Pop Culture",
    businessCategory: "Business",
    scienceCategory: "Science",
    techCategory: "Tech",
    worldCategory: "World",
    home: "Home",
    searchMarkets: "Search markets...",
    activeMarkets: "active markets",
    tryAgain: "Try again",
    noMarketsFound: "No markets found. Try a different category or search.",
    poweredBy: "Powered by Polymarket",
    yourPortfolio: "Your Portfolio",
    demo: "Demo",
    availableBalance: "Available Balance",
    yesWagered: "YES Wagered",
    noWagered: "NO Wagered",
    total: "Total",
    activity: "Activity",
    myBets: "My Bets",
    liveMarketActivity: "Live market activity",
    noBetsYet: "No bets yet",
    noBetsHelp: "Click Buy Yes or Buy No on any market card",
    wagered: "Wagered",
    confirmBet: "Confirm Bet",
    amount: "Amount",
    price: "Price",
    potentialPayout: "Potential payout",
    balanceAfter: "Balance after",
    betPlaced: "Bet placed:",
    onOutcome: "on",
    academyBadge: "Free Learning Resources",
    academyTitle: "Prediction Markets Academy",
    academySubtitle:
      "Master the fundamentals of prediction trading. From basic concepts to advanced strategies, learn everything you need before risking real capital.",
    backToAllCourses: "Back to All Courses",
    allCourses: "All Courses",
    readArticle: "Read Article",
    learnByDoing: "Learn by Doing",
    academyCtaText:
      "Theory is great, but practice makes perfect. Apply everything you learn in our risk-free simulator with real Polymarket data.",
    visitPolymarket: "Visit Polymarket",
    readyToApply: "Ready to apply what you learned?",
    practiceWithVirtualFunds: "Practice with virtual funds on real market data.",
    startPracticing: "Start Practicing",
    fundamentalsCategory: "Fundamentals",
    deepDiveCategory: "Deep Dive",
    strategiesCategory: "Strategies",
    platformCategory: "Platform Guide",
    beginnerLevel: "Beginner",
    intermediateLevel: "Intermediate",
  },
  es: {
    navMarkets: "Mercados",
    navAcademy: "Academia",
    navHowItWorks: "Como funciona",
    navCommunity: "Comunidad",
    poweredByPolymarket: "Powered by Polymarket",
    demoTrading: "Trading Demo",
    signOut: "Cerrar sesion",
    logIn: "Iniciar sesion",
    getStarted: "Comenzar",
    closeMenu: "Cerrar menu",
    openMenu: "Abrir menu",
    poweredByPolymarketApi: "Powered by Polymarket API",
    liveData: "Datos en vivo",
    heroTitleLine1: "Paper Trading",
    heroTitleLine2: "para Polymarket",
    heroSubtitle:
      "Aprende a operar en mercados de prediccion sin arriesgar dinero real. Practica con datos en vivo de Polymarket y domina las probabilidades antes de invertir.",
    startPredicting: "Empezar a predecir",
    browseMarkets: "Ver mercados",
    signIn: "Iniciar sesion",
    or: "o",
    createAccount: "Crear cuenta",
    accountHint: "Crea una cuenta gratis para seguir tu progreso y guardar tu portafolio.",
    zeroRisk: "Riesgo financiero cero",
    realPrices: "Precios reales de Polymarket",
    paperMode: "Modo Paper Trading",
    product: "Producto",
    resources: "Recursos",
    legal: "Legal",
    company: "Empresa",
    footerBrandDesc: "Simulador gratuito de mercados de prediccion con datos reales de Polymarket.",
    helpCenter: "Centro de ayuda",
    documentation: "Documentacion",
    blog: "Blog",
    tutorials: "Tutoriales",
    terms: "Terminos del servicio",
    privacy: "Politica de privacidad",
    riskDisclosure: "Aviso de riesgo",
    about: "Nosotros",
    careers: "Carreras",
    press: "Prensa",
    contact: "Contacto",
    attrTitle: "Powered by Polymarket",
    attrTextPrefix: "Todos los datos de mercado vienen de",
    attrTextMiddle: ", el principal mercado descentralizado de prediccion. Listo para operar con fondos reales?",
    attrTextLink2: "Visita Polymarket directamente",
    allRightsReserved: "Todos los derechos reservados.",
    dataPoweredBy: "Datos impulsados por",
    welcomeBack: "Bienvenido de nuevo",
    loginDescription: "Inicia sesion para acceder a la demo de mercados de prediccion",
    password: "Contrasena",
    enterPassword: "Introduce tu contrasena",
    signingIn: "Iniciando sesion...",
    dontHaveAccount: "No tienes cuenta?",
    backToHome: "Volver al inicio",
    virtualFundsNotice:
      "Al iniciar sesion, aceptas practicar solo con fondos virtuales. No se usa dinero real.",
    createAccountTitle: "Crear cuenta",
    signUpDescription: "Empieza a practicar con $100,000 en fondos virtuales",
    displayName: "Nombre para mostrar",
    optional: "opcional",
    yourNickname: "Tu apodo",
    min6Chars: "Min. 6 caracteres",
    confirmPassword: "Confirmar contrasena",
    repeatPassword: "Repite tu contrasena",
    creatingAccount: "Creando cuenta...",
    whatYouGet: "Lo que obtienes:",
    benefitBalance: "Saldo virtual de $100,000",
    benefitRealtime: "Datos de mercados en tiempo real",
    benefitPractice: "Practica trading sin riesgo",
    benefitTrack: "Sigue tu rendimiento",
    alreadyHaveAccount: "Ya tienes cuenta?",
    createAccountNotice:
      "Al crear una cuenta, aceptas practicar solo con fondos virtuales. No se usa dinero real.",
    passwordsDontMatch: "Las contrasenas no coinciden",
    passwordTooShort: "La contrasena debe tener al menos 6 caracteres",
    authUnexpectedError: "Ocurrio un error",
    checkYourEmail: "Revisa tu email",
    sentConfirmationLink: "Te enviamos un enlace de confirmacion",
    verifyEmailHelp:
      "Haz clic en el enlace de tu email para verificar tu cuenta y empezar a operar con fondos virtuales.",
    didntReceiveEmail: "No recibiste un email? Revisa spam o",
    tryAgain: "intentalo de nuevo",
    backToLogin: "Volver al login",
    authSomethingWrong: "Algo salio mal",
    authUnexpectedErrorLong: "Ocurrio un error inesperado durante la autenticacion.",
    errorPrefix: "Error:",
    goDemo: "Entrar a demo",
    authPanelTitle: "Panel de acceso a la demo",
    authPanelDescription: "Crea tu cuenta o inicia sesion para usar el simulador",
    loginTab: "Iniciar sesion",
    signupTab: "Crear cuenta",
    startDemoTrading: "Empezar demo trading",
    startsWithFunds: "Empieza con $100,000 en fondos virtuales",
    tradeRealWorldEvents: "Opera eventos del mundo real con mercados de prediccion",
    predictionMarkets: "Mercados de prediccion",
    realMarketsPowered: "Mercados reales impulsados por Polymarket",
    loadingMarkets: "Cargando mercados...",
    marketsAvailable: "mercados disponibles",
    portfolio: "Portafolio",
    balance: "Balance",
    invested: "Invertido",
    positions: "Posiciones",
    recentTrades: "Ultimas operaciones",
    shares: "participaciones",
    placeOrder: "Crear orden",
    placeOrderDesc: "Opera este mercado de prediccion con tu balance demo.",
    yes: "Si",
    no: "No",
    chance: "probabilidad",
    amountUsd: "Cantidad (USD)",
    pricePerShare: "Precio por participacion",
    maxReturn: "Retorno maximo",
    buyYes: "Comprar Si",
    buyNo: "Comprar No",
    insufficientBalance: "Balance insuficiente. Disponible:",
    unknown: "Desconocido",
    other: "Otro",
    ended: "Finalizado",
    today: "Hoy",
    tomorrow: "Manana",
    tbd: "Por definir",
    allCategory: "Todas",
    politicsCategory: "Politica",
    sportsCategory: "Deportes",
    cryptoCategory: "Crypto",
    popCultureCategory: "Cultura Pop",
    businessCategory: "Negocios",
    scienceCategory: "Ciencia",
    techCategory: "Tecnologia",
    worldCategory: "Mundo",
    home: "Inicio",
    searchMarkets: "Buscar mercados...",
    activeMarkets: "mercados activos",
    tryAgain: "Intentar de nuevo",
    noMarketsFound: "No se encontraron mercados. Prueba otra categoria o busqueda.",
    poweredBy: "Powered by Polymarket",
    yourPortfolio: "Tu portafolio",
    demo: "Demo",
    availableBalance: "Balance disponible",
    yesWagered: "SI apostado",
    noWagered: "NO apostado",
    total: "Total",
    activity: "Actividad",
    myBets: "Mis apuestas",
    liveMarketActivity: "Actividad en vivo del mercado",
    noBetsYet: "Aun no hay apuestas",
    noBetsHelp: "Haz clic en Comprar Si o Comprar No en cualquier mercado",
    wagered: "Apostado",
    confirmBet: "Confirmar apuesta",
    amount: "Cantidad",
    price: "Precio",
    potentialPayout: "Pago potencial",
    balanceAfter: "Balance despues",
    betPlaced: "Apuesta realizada:",
    onOutcome: "en",
    academyBadge: "Recursos de aprendizaje gratis",
    academyTitle: "Academia de mercados de prediccion",
    academySubtitle:
      "Domina los fundamentos del prediction trading. Desde conceptos basicos hasta estrategias avanzadas, aprende todo antes de arriesgar capital real.",
    backToAllCourses: "Volver a todos los cursos",
    allCourses: "Todos los cursos",
    readArticle: "Leer articulo",
    learnByDoing: "Aprende practicando",
    academyCtaText:
      "La teoria es genial, pero la practica perfecciona. Aplica todo lo que aprendes en nuestro simulador sin riesgo con datos reales de Polymarket.",
    visitPolymarket: "Visitar Polymarket",
    readyToApply: "Listo para aplicar lo aprendido?",
    practiceWithVirtualFunds: "Practica con fondos virtuales sobre datos reales de mercado.",
    startPracticing: "Empezar a practicar",
    fundamentalsCategory: "Fundamentos",
    deepDiveCategory: "Profundizacion",
    strategiesCategory: "Estrategias",
    platformCategory: "Guia de plataforma",
    beginnerLevel: "Principiante",
    intermediateLevel: "Intermedio",
  },
};

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const saved = window.localStorage.getItem("predictiontrade_language");
    if (saved === "en" || saved === "es") {
      setLanguage(saved);
    }
  }, []);

  const handleSetLanguage = (nextLanguage: Language) => {
    setLanguage(nextLanguage);
    window.localStorage.setItem("predictiontrade_language", nextLanguage);
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage: handleSetLanguage,
      t: (key: string) => dictionaries[language][key] ?? key,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
