"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Language = "en" | "es";

type Dictionary = Record<string, string>;

const dictionaries: Record<Language, Dictionary> = {
  en: {
    navMarkets: "Markets",
    navAcademy: "Academy",
    navHowItWorks: "How It Works",
    navCommunity: "Community",
    navGame: "Game",
    navLeaderboard: "Leaderboard",
    navDashboard: "Dashboard",
    navMyDashboard: "My Dashboard",
    navActivity: "Activity",
    navProfile: "Profile",
    poweredByPolymarket: "Powered by Polymarket",
    demoTrading: "Predict",
    signOut: "Sign out",
    logIn: "Log In",
    getStarted: "Get Started",
    closeMenu: "Close menu",
    openMenu: "Open menu",
    emailLabel: "Email",
    poweredByPolymarketApi: "Powered by Polymarket API",
    liveData: "Live Data",
    heroTitleLine1: "Predict the Future.",
    heroTitleLine2: "Prove You're Right.",
    heroSubtitle:
      "Make public predictions on real-world events. Build your streak, earn badges, and climb the leaderboard — all with $100,000 in virtual funds.",
    startPredicting: "Start Predicting",
    browseMarkets: "Browse Markets",
    signIn: "Sign in",
    or: "or",
    createAccount: "Create account",
    accountHint: "Create a free account to save your predictions and track your accuracy.",
    zeroRisk: "Public Predictions",
    realPrices: "Real Market Data",
    paperMode: "Build Your Streak",
    product: "Product",
    resources: "Resources",
    legal: "Legal",
    company: "Company",
    footerBrandDesc: "Build a public forecasting track record on real Polymarket events. Virtual funds, real reputation.",
    helpCenter: "Help Center",
    documentation: "Documentation",
    blog: "Blog",
    tutorials: "Tutorials",
    terms: "Terms of Service",
    privacy: "Privacy Policy",
    riskDisclosure: "Demo notice",
    about: "About Us",
    careers: "Careers",
    press: "Press",
    contact: "Contact",
    attrTitle: "Powered by Polymarket",
    attrTextPrefix: "All market data comes from",
    attrTextMiddle: ", the leading decentralized prediction market. Want to predict with real funds?",
    attrTextLink2: "Visit Polymarket directly",
    allRightsReserved: "All rights reserved.",
    dataPoweredBy: "Data powered by",
    welcomeBack: "Welcome back",
    loginDescription: "Sign in to make predictions and build your track record.",
    password: "Password",
    enterPassword: "Enter your password",
    signingIn: "Signing in...",
    dontHaveAccount: "Don't have an account?",
    backToHome: "Back to home",
    virtualFundsNotice:
      "By signing in, you agree to make predictions with a virtual balance only. No real money is involved.",
    createAccountTitle: "Create account",
    signUpDescription: "Start with a $100,000 virtual balance and make your first call",
    displayName: "Display Name",
    optional: "optional",
    yourNickname: "Your nickname",
    min6Chars: "Min. 6 characters",
    confirmPassword: "Confirm Password",
    repeatPassword: "Repeat your password",
    creatingAccount: "Creating account...",
    whatYouGet: "What you get:",
    benefitBalance: "$100,000 virtual balance",
    benefitRealtime: "Real-time prediction market data",
    benefitPractice: "Make predictions risk-free",
    benefitTrack: "Track your performance",
    alreadyHaveAccount: "Already have an account?",
    createAccountNotice:
      "By creating an account, you agree to make predictions with a virtual balance only. No real money is involved.",
    passwordsDontMatch: "Passwords do not match",
    passwordTooShort: "Password must be at least 6 characters",
    authUnexpectedError: "An error occurred",
    checkYourEmail: "Check your email",
    sentConfirmationLink: "We sent you a confirmation link",
    verifyEmailHelp:
      "Click the link in your email to verify your account and make your first prediction.",
    didntReceiveEmail: "Didn't receive an email? Check your spam folder or",
    tryAgainLink: "try again",
    backToLogin: "Back to login",
    authSomethingWrong: "Something went wrong",
    authUnexpectedErrorLong: "An unexpected error occurred during authentication.",
    errorPrefix: "Error:",
    goDemo: "Enter demo",
    authPanelTitle: "Demo access panel",
    authPanelDescription: "Create your account or sign in to use the simulator",
    loginTab: "Sign in",
    signupTab: "Create account",
    startDemoTrading: "Start Demo Trading",
    startsWithFunds: "Starts with $100,000 in virtual funds",
    tradeRealWorldEvents: "Trade on real-world events with prediction markets",
    predictionMarkets: "Prediction Markets",
    realMarketsPowered: "Real markets powered by Polymarket",
    loadingMarkets: "Loading markets...",
    marketsAvailable: "markets available",
    portfolio: "Portfolio",
    balance: "Balance",
    invested: "Invested",
    positions: "Positions",
    recentTrades: "Recent Trades",
    shares: "shares",
    placeOrder: "Place Order",
    placeOrderDesc: "Trade on this prediction market with your demo balance.",
    yes: "Yes",
    no: "No",
    chance: "chance",
    amountUsd: "Amount (USD)",
    pricePerShare: "Price per share",
    maxReturn: "Max return",
    buyYes: "Buy Yes",
    buyNo: "Buy No",
    insufficientBalance: "Insufficient balance. Available:",
    unknown: "Unknown",
    other: "Other",
    ended: "Ended",
    today: "Today",
    tomorrow: "Tomorrow",
    tbd: "TBD",
    allCategory: "All",
    politicsCategory: "Politics",
    sportsCategory: "Sports",
    cryptoCategory: "Crypto",
    popCultureCategory: "Pop Culture",
    businessCategory: "Business",
    scienceCategory: "Science",
    techCategory: "Tech",
    worldCategory: "World",
    home: "Home",
    searchMarkets: "Search markets...",
    activeMarkets: "active markets",
    tryAgain: "Try again",
    noMarketsFound: "No markets found. Try a different category or search.",
    poweredBy: "Powered by Polymarket",
    yourPortfolio: "Your Portfolio",
    demo: "Demo",
    availableBalance: "Available Balance",
    yesWagered: "YES Wagered",
    noWagered: "NO Wagered",
    total: "Total",
    activity: "Activity",
    myBets: "My Bets",
    liveMarketActivity: "Live market activity",
    noBetsYet: "No bets yet",
    noBetsHelp: "Click Buy Yes or Buy No on any market card",
    wagered: "Wagered",
    confirmBet: "Confirm Bet",
    amount: "Amount",
    price: "Price",
    potentialPayout: "Potential payout",
    balanceAfter: "Balance after",
    betPlaced: "Bet placed:",
    onOutcome: "on",
    academyBadge: "Free Learning Resources",
    academyTitle: "Prediction Markets Academy",
    academySubtitle:
      "Master the fundamentals of prediction trading. From basic concepts to advanced strategies, learn everything you need before risking real capital.",
    backToAllCourses: "Back to All Courses",
    allCourses: "All Courses",
    readArticle: "Read Article",
    learnByDoing: "Learn by Doing",
    academyCtaText:
      "Theory is great, but practice makes perfect. Apply everything you learn in our risk-free simulator with real Polymarket data.",
    visitPolymarket: "Visit Polymarket",
    readyToApply: "Ready to apply what you learned?",
    practiceWithVirtualFunds: "Practice with virtual funds on real market data.",
    startPracticing: "Start Practicing",
    fundamentalsCategory: "Fundamentals",
    deepDiveCategory: "Deep Dive",
    strategiesCategory: "Strategies",
    platformCategory: "Platform Guide",
    beginnerLevel: "Beginner",
    intermediateLevel: "Intermediate",
  },
  es: {
    navMarkets: "Mercados",
    navAcademy: "Academia",
    navHowItWorks: "Cómo funciona",
    navCommunity: "Comunidad",
    navGame: "Juego",
    navLeaderboard: "Ranking",
    navDashboard: "Panel",
    navMyDashboard: "Mi panel",
    navActivity: "Actividad",
    navProfile: "Perfil",
    poweredByPolymarket: "Datos de Polymarket",
    demoTrading: "Predecir",
    signOut: "Cerrar sesión",
    logIn: "Iniciar sesión",
    getStarted: "Comenzar",
    closeMenu: "Cerrar menú",
    openMenu: "Abrir menú",
    emailLabel: "Correo",
    poweredByPolymarketApi: "Con API de Polymarket",
    liveData: "Datos en vivo",
    heroTitleLine1: "Predice el futuro.",
    heroTitleLine2: "Demuestra que tienes razón.",
    heroSubtitle:
      "Haz predicciones públicas sobre eventos reales. Construye tu racha, gana insignias y escala el ranking — con $100.000 en fondos virtuales.",
    startPredicting: "Empezar a predecir",
    browseMarkets: "Explorar mercados",
    signIn: "Iniciar sesión",
    or: "o",
    createAccount: "Crear cuenta",
    accountHint: "Crea una cuenta gratis para guardar tus predicciones y seguir tu precisión.",
    zeroRisk: "Predicciones públicas",
    realPrices: "Datos de mercado reales",
    paperMode: "Construye tu racha",
    product: "Producto",
    resources: "Recursos",
    legal: "Legal",
    company: "Empresa",
    footerBrandDesc: "Construye un historial público como predictor con eventos reales de Polymarket. Fondos virtuales, reputación real.",
    helpCenter: "Centro de ayuda",
    documentation: "Documentación",
    blog: "Blog",
    tutorials: "Tutoriales",
    terms: "Términos del servicio",
    privacy: "Política de privacidad",
    riskDisclosure: "Aviso de demo",
    about: "Sobre nosotros",
    careers: "Empleo",
    press: "Prensa",
    contact: "Contacto",
    attrTitle: "Datos de Polymarket",
    attrTextPrefix: "Todos los datos de mercado provienen de",
    attrTextMiddle: ", el principal mercado descentralizado de predicción. ¿Quieres predecir con fondos reales?",
    attrTextLink2: "Visita Polymarket directamente",
    allRightsReserved: "Todos los derechos reservados.",
    dataPoweredBy: "Datos provistos por",
    welcomeBack: "Bienvenido de nuevo",
    loginDescription: "Inicia sesión para hacer predicciones y construir tu historial.",
    password: "Contraseña",
    enterPassword: "Introduce tu contraseña",
    signingIn: "Iniciando sesión...",
    dontHaveAccount: "¿No tienes cuenta?",
    backToHome: "Volver al inicio",
    virtualFundsNotice:
      "Al iniciar sesión, aceptas hacer predicciones solo con un saldo virtual. No se usa dinero real.",
    createAccountTitle: "Crear cuenta",
    signUpDescription: "Empieza con un saldo virtual de $100.000 y haz tu primera predicción",
    displayName: "Nombre para mostrar",
    optional: "opcional",
    yourNickname: "Tu apodo",
    min6Chars: "Mín. 6 caracteres",
    confirmPassword: "Confirmar contraseña",
    repeatPassword: "Repite tu contraseña",
    creatingAccount: "Creando cuenta...",
    whatYouGet: "Lo que obtienes:",
    benefitBalance: "Saldo virtual de $100.000",
    benefitRealtime: "Datos de mercados en tiempo real",
    benefitPractice: "Predice sin riesgo",
    benefitTrack: "Sigue tu rendimiento",
    alreadyHaveAccount: "¿Ya tienes cuenta?",
    createAccountNotice:
      "Al crear una cuenta, aceptas hacer predicciones solo con un saldo virtual. No se usa dinero real.",
    passwordsDontMatch: "Las contraseñas no coinciden",
    passwordTooShort: "La contraseña debe tener al menos 6 caracteres",
    authUnexpectedError: "Ocurrió un error",
    checkYourEmail: "Revisa tu correo",
    sentConfirmationLink: "Te enviamos un enlace de confirmación",
    verifyEmailHelp:
      "Haz clic en el enlace de tu correo para verificar tu cuenta y hacer tu primera predicción.",
    didntReceiveEmail: "¿No recibiste el correo? Revisa la carpeta de spam o",
    tryAgainLink: "inténtalo de nuevo",
    backToLogin: "Volver al inicio de sesión",
    authSomethingWrong: "Algo salió mal",
    authUnexpectedErrorLong: "Ocurrió un error inesperado durante la autenticación.",
    errorPrefix: "Error:",
    goDemo: "Entrar al simulador",
    authPanelTitle: "Acceso al simulador",
    authPanelDescription: "Crea tu cuenta o inicia sesión para usar el simulador",
    loginTab: "Iniciar sesión",
    signupTab: "Crear cuenta",
    startDemoTrading: "Empezar trading demo",
    startsWithFunds: "Empieza con $100.000 en fondos virtuales",
    tradeRealWorldEvents: "Opera sobre eventos reales con mercados de predicción",
    predictionMarkets: "Mercados de predicción",
    realMarketsPowered: "Mercados reales con datos de Polymarket",
    loadingMarkets: "Cargando mercados...",
    marketsAvailable: "mercados disponibles",
    portfolio: "Portafolio",
    balance: "Balance",
    invested: "Invertido",
    positions: "Posiciones",
    recentTrades: "Operaciones recientes",
    shares: "participaciones",
    placeOrder: "Crear orden",
    placeOrderDesc: "Opera este mercado de predicción con tu balance demo.",
    yes: "Sí",
    no: "No",
    chance: "probabilidad",
    amountUsd: "Cantidad (USD)",
    pricePerShare: "Precio por participación",
    maxReturn: "Retorno máximo",
    buyYes: "Comprar Sí",
    buyNo: "Comprar No",
    insufficientBalance: "Balance insuficiente. Disponible:",
    unknown: "Desconocido",
    other: "Otro",
    ended: "Finalizado",
    today: "Hoy",
    tomorrow: "Mañana",
    tbd: "Por definir",
    allCategory: "Todas",
    politicsCategory: "Política",
    sportsCategory: "Deportes",
    cryptoCategory: "Cripto",
    popCultureCategory: "Cultura pop",
    businessCategory: "Negocios",
    scienceCategory: "Ciencia",
    techCategory: "Tecnología",
    worldCategory: "Mundo",
    home: "Inicio",
    searchMarkets: "Buscar mercados...",
    activeMarkets: "mercados activos",
    noMarketsFound: "No se encontraron mercados. Prueba otra categoría o búsqueda.",
    poweredBy: "Datos de Polymarket",
    yourPortfolio: "Tu portafolio",
    demo: "Demo",
    availableBalance: "Balance disponible",
    yesWagered: "SÍ apostado",
    noWagered: "NO apostado",
    total: "Total",
    activity: "Actividad",
    myBets: "Mis apuestas",
    liveMarketActivity: "Actividad del mercado en vivo",
    noBetsYet: "Aún no tienes apuestas",
    noBetsHelp: "Haz clic en Comprar Sí o Comprar No en cualquier mercado",
    wagered: "Apostado",
    confirmBet: "Confirmar apuesta",
    amount: "Cantidad",
    price: "Precio",
    potentialPayout: "Pago potencial",
    balanceAfter: "Balance después",
    betPlaced: "Apuesta realizada:",
    onOutcome: "en",
    academyBadge: "Recursos de aprendizaje gratuitos",
    academyTitle: "Academia de mercados de predicción",
    academySubtitle:
      "Domina los fundamentos del trading de predicción. Desde conceptos básicos hasta estrategias avanzadas, aprende todo antes de arriesgar capital real.",
    backToAllCourses: "Volver a todos los cursos",
    allCourses: "Todos los cursos",
    readArticle: "Leer artículo",
    learnByDoing: "Aprende practicando",
    academyCtaText:
      "La teoría es genial, pero la práctica es la que perfecciona. Aplica todo lo que aprendes en nuestro simulador sin riesgo con datos reales de Polymarket.",
    visitPolymarket: "Visitar Polymarket",
    readyToApply: "¿Listo para aplicar lo aprendido?",
    practiceWithVirtualFunds: "Practica con fondos virtuales y datos reales de mercado.",
    startPracticing: "Empezar a practicar",
    fundamentalsCategory: "Fundamentos",
    deepDiveCategory: "Profundización",
    strategiesCategory: "Estrategias",
    platformCategory: "Guía de la plataforma",
    beginnerLevel: "Principiante",
    intermediateLevel: "Intermedio",
  },
};

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const saved = window.localStorage.getItem("predictiontrade_language");
    if (saved === "en" || saved === "es") {
      setLanguage(saved);
    }
  }, []);

  const handleSetLanguage = (nextLanguage: Language) => {
    setLanguage(nextLanguage);
    window.localStorage.setItem("predictiontrade_language", nextLanguage);
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage: handleSetLanguage,
      t: (key: string) => dictionaries[language][key] ?? key,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
