// ─── Types ────────────────────────────────────────────────────────────────────
// This interface is the stable contract between components and the copy layer.
// When Phase 4g adds Claude API, the same interface is returned — components
// never change, only the generator implementation changes.

export interface ShareCopy {
  x: string        // ≤280 chars, ready for x.com/intent/tweet?text=
  whatsapp: string // conversational, for wa.me/?text= encoding
  text: string     // plain copy for clipboard (no platform assumption)
}

export type ShareType = "called-it" | "streak-milestone" | "leaderboard-climb"

export interface CalledItData {
  username: string
  marketTitle: string
  prediction: "YES" | "NO"
  isContrarian: boolean
  accuracyPct?: number | null
  currentStreak?: number
}

export interface StreakMilestoneData {
  username: string
  streak: number
}

export interface LeaderboardClimbData {
  username: string
  previousRank: number
  currentRank: number
  accuracyPct?: number | null
}

export type ShareData = CalledItData | StreakMilestoneData | LeaderboardClimbData

// ─── Internal helpers ─────────────────────────────────────────────────────────

const BASE = "predictiontrade.online"

function pick<T>(arr: T[], seed: string): T {
  const h = seed.split("").reduce((acc, c) => acc + c.charCodeAt(0), 0)
  return arr[h % arr.length]
}

function trunc(s: string, max: number): string {
  return s.length <= max ? s : s.slice(0, max - 1) + "…"
}

// ─── Called It ────────────────────────────────────────────────────────────────

function calledItCopy(d: CalledItData): ShareCopy {
  const title = trunc(d.marketTitle, 70)
  const acc   = d.accuracyPct ? ` ${d.accuracyPct}% accuracy.` : ""
  const crowd  = d.isContrarian ? " Against the crowd." : ""

  const xVariants = [
    `Called it. "${title}" — I said ${d.prediction}.${crowd}${acc} ${BASE}`,
    `🎯 ${d.prediction} on "${title}"${d.isContrarian ? " when 80% disagreed 🎲" : ""}.${acc} ${BASE}`,
  ]

  const waVariants = [
    `Just called ${title} correctly${d.isContrarian ? " — against 80% of the crowd" : ""}.${acc} Come predict with me → ${BASE}`,
    `I said ${d.prediction} on "${title}" and nailed it${d.isContrarian ? " (contrarian call!)" : ""}.${acc} ${BASE}`,
  ]

  const seed = d.marketTitle + d.prediction
  const x = pick(xVariants, seed)
  const whatsapp = pick(waVariants, seed)
  return { x, whatsapp, text: x }
}

// ─── Streak Milestone ─────────────────────────────────────────────────────────

function streakMilestoneCopy(d: StreakMilestoneData): ShareCopy {
  const { streak } = d
  const emoji    = streak >= 30 ? "🏆" : streak >= 7 ? "⚡" : "🔥"
  const context  = streak >= 30 ? "a prediction machine" : streak >= 7 ? "one full week" : "building momentum"

  const x = `${emoji} ${streak}-day prediction streak on @PredictionTrade — ${context}. Can you beat me? ${BASE}`
  const whatsapp = `I've predicted ${streak} days in a row on PredictionTrade. ${streak >= 7 ? "Come compete" : "Join me"} → ${BASE}`

  return { x, whatsapp, text: x }
}

// ─── Leaderboard Climb ────────────────────────────────────────────────────────

function leaderboardClimbCopy(d: LeaderboardClimbData): ShareCopy {
  const moved = d.previousRank - d.currentRank
  const acc   = d.accuracyPct ? ` ${d.accuracyPct}% accuracy.` : ""

  const xVariants = [
    `Climbed from #${d.previousRank} → #${d.currentRank} on the PredictionTrade leaderboard (+${moved} spots).${acc} ${BASE}/leaderboard`,
    `Up ${moved} spots. Now #${d.currentRank} on @PredictionTrade.${acc} ${BASE}/leaderboard`,
  ]

  const seed = `${d.previousRank}-${d.currentRank}`
  const x = pick(xVariants, seed)
  const whatsapp = `I'm now #${d.currentRank} on the PredictionTrade leaderboard (was #${d.previousRank}). Come compete → ${BASE}/leaderboard`

  return { x, whatsapp, text: x }
}

// ─── Main export ──────────────────────────────────────────────────────────────
// Single synchronous function — always instant, no network, no cost.
// Phase 4g upgrade path: components call /api/ai/share-copy which returns the
// same ShareCopy shape — generated by Claude when ANTHROPIC_API_KEY is set.

export function generateShareCopy(type: "called-it", data: CalledItData): ShareCopy
export function generateShareCopy(type: "streak-milestone", data: StreakMilestoneData): ShareCopy
export function generateShareCopy(type: "leaderboard-climb", data: LeaderboardClimbData): ShareCopy
export function generateShareCopy(type: ShareType, data: ShareData): ShareCopy {
  switch (type) {
    case "called-it":        return calledItCopy(data as CalledItData)
    case "streak-milestone": return streakMilestoneCopy(data as StreakMilestoneData)
    case "leaderboard-climb":return leaderboardClimbCopy(data as LeaderboardClimbData)
  }
}
